define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid;
    var dialog = require('./dialog');
    var o={};
    
    o.init = function(domid){
        gridid = domid;
        var stateOpts = dict.getOptions("rscState",{text:"全部",value:-1});
        var cateOpts = dict.getOptions("category",{text:"全部",value:-1});
        store = new mwt.Store({
            proxy: new mwt.HttpProxy({
                //beforeLoad : store_before_load,
                //afterLoad  : store_after_load,
                url : ajax.getAjaxUrl("queryResource")
            })
        });
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            pagebar     : true,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : true,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : false,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            bodyStyle   : '', 
            tbarStyle   : 'margin:2px 0 10px;',
            tbar: [
                {type:'select',id:"state-sel-"+gridid,label:"状态",value:'-1',options:stateOpts,handler:o.query},
                {type:'search',id:'so-key-'+gridid,width:300,handler:o.query,placeholder:'搜索关键词'},
                '->',
                {label:'<i class="sicon-plus"></i> 新增资源',cls:'mwt-btn-success',handler:function(){
                    dialog.open({id:0},o.query);
                }}
            ],
            cm: new MWT.Grid.ColumnModel([
                {head:'资源ID',dataIndex:'id',width:60,align:'left',sort:true,render:function(v,item){
                    return '#'+v;
                }},
                {head:'图标',dataIndex:'icon',width:60,align:'center',sort:false,render:function(v,item){
                    return '<img src="'+v+'" class="mwt-image-view" style="width:40px;height:40px;">';
                }},
                {head:'资源标题',dataIndex:'title',width:120,align:'left',sort:false,render:function(v,item){
                    return '<a href="'+item.url+'" target="_blank">'+v+'</a>';
                }},
                {head:'分类',dataIndex:'cateid',width:90,align:'center',sort:true,render:function(v,item){
                    return item.catename;
                }},/*
                {head:'介绍(支持markdown)',dataIndex:'info',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'资源介绍',dataIndex:'info',align:'left',sort:false,render:function(v,item){
                    return '<span style="color:#999;">'+v+'</span>';
                }},
                {head:'资源链接',dataIndex:'url',align:'left',width:150,sort:false,render:function(v,item){
                    return '<a href="'+item.url+'" target="_blank">'+v+'</a>';
                }},
                // {head:'资源链接类型(1:下载链接;2:跳转链接)',dataIndex:'urltype',width:120,align:'left',sort:false,render:function(v,item){
                //     var checked = (v==1) ? 'checked' : '';
                //    var code = '<label class="mwt-cbx-switch-plain" style="width:40px;height:18px;">'+
                //         '<input name="adenable" type="checkbox" data-dtname="'+item.id+'" '+checked+'>'+
                //     '<span><i></i></span></label>';
                //     return code;
                // }},
                {head:'资源大小',dataIndex:'size',width:80,align:'right',sort:true,render:function(v,item){
                    return v;
                }},
                {head:'下载次数',dataIndex:'downnum',width:80,align:'right',sort:true,render:function(v,item){
                    return v;
                }},/*
                {head:'资源所需积分',dataIndex:'credits',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'状态',dataIndex:'status',width:70,align:'center',sort:true,render:function(v,item){
                    var checked = (v==1) ? 'checked' : ''; 
                   var code = '<label class="mwt-cbx-switch-plain" style="width:40px;height:18px;">'+
                        '<input name="adenable" type="checkbox" data-dtname="'+item.id+'" '+checked+'>'+
                    '<span><i></i></span></label>';
                    return code;
                }},
                /*{head:'添加记录的用户ID',dataIndex:'cuid',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'创建时间',dataIndex:'ctime',width:120,align:'center',sort:true,render:mwt.GridRender.datetime},
                /*{head:'修改记录的用户ID',dataIndex:'muid',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'操作',dataIndex:'id',align:'right',width:80,sort:false,render:function(v,item){
                    var editbtn = '<a name="editbtn-'+gridid+'" data-id="'+v+'" href="javascript:;">编辑</a>';
                    var delbtn = '<a name="delbtn-'+gridid+'" data-id="'+v+'" href="javascript:;">删除</a>';
                    var btns = [editbtn,delbtn];
                    return btns.join("&nbsp;&nbsp;");
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 启用开关
            jQuery('[name=adenable]').unbind('change').change(function(){
                var id = jQuery(this).data('dtname');
                var enable = jQuery(this).is(':checked') ? 1 : 0;
                ajax.post('setStatus',{id:id,status:enable},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                    mwt.notify('已保存',1500,'success');
                });
            });
        });
        grid.create();
        o.query();
    };

    // 查询
    o.query = function() {
        store.baseParams = {
            cateid: 0,
            state: mwt.get_select_value("state-sel-"+gridid),
            key: mwt.get_value("so-key-"+gridid)
        };
        grid.load();
    };

    // 编辑按钮点击事件
    function editbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        var item = grid.getRecord('id',id);
        dialog.open(item,o.query);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('removeResource',{id:id},function(res){
                if (res.retcode!=0) mwt.alert(res.retmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
