<?php
 
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}
global $comiis_config, $comiis_portal;
$comiis_config = array(
	'name' => $comiis_portal['gezi07_a'],
	'dir' => 'gezi07',
	'copyright' => 'http://www.comiis.com',
	'version' => '2',
	'types' => '3',
	'install' => array('block'=>array('0'=>array( 'bid'=>0, 'blockclass'=>'html_html', 'blocktype'=>'1', 'name'=>'comiis', 'title'=>'', 'classname'=>'', 'summary'=>'<div class="comiis_mh_gz04 cl"><a href="#" class="f_f" style="background:#FF9900"><img src="source/plugin/comiis_app_portal/image/001.png" class="vm"><h2>'.$comiis_portal['gezi07_b'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_c'].'</span></a><a href="#" class="f_f" style="background:#82c508"><img src="source/plugin/comiis_app_portal/image/002.png" class="vm"><h2>'.$comiis_portal['gezi07_d'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_e'].'</span></a><a href="#" class="f_f" style="background:#20b4ff"><img src="source/plugin/comiis_app_portal/image/003.png" class="vm"><h2>'.$comiis_portal['gezi07_f'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_g'].'</span></a><a href="#" class="f_f" style="background:#FF705E"><img src="source/plugin/comiis_app_portal/image/004.png" class="vm"><h2>'.$comiis_portal['gezi07_h'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_i'].'</span></a></div>', 'uid'=>'0', 'username'=>'comiis', 'styleid'=>'0', 'blockstyle'=>'', 'picwidth'=>'0', 'picheight'=>'0', 'target'=>'blank', 'dateformat'=>'Y-m-d', 'dateuformat'=>'0', 'script'=>'blank', 'param'=>array( 'content'=>'<div class="comiis_mh_gz04 cl"><a href="#" class="f_f" style="background:#FF9900"><img src="source/plugin/comiis_app_portal/image/001.png" class="vm"><h2>'.$comiis_portal['gezi07_b'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_c'].'</span></a><a href="#" class="f_f" style="background:#82c508"><img src="source/plugin/comiis_app_portal/image/002.png" class="vm"><h2>'.$comiis_portal['gezi07_d'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_e'].'</span></a><a href="#" class="f_f" style="background:#20b4ff"><img src="source/plugin/comiis_app_portal/image/003.png" class="vm"><h2>'.$comiis_portal['gezi07_f'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_g'].'</span></a><a href="#" class="f_f" style="background:#FF705E"><img src="source/plugin/comiis_app_portal/image/004.png" class="vm"><h2>'.$comiis_portal['gezi07_h'].'</h2><span class="comiis_mh_xifont">'.$comiis_portal['gezi07_i'].'</span></a></div>', 'items'=>10,), 'shownum'=>'10', 'cachetime'=>'0', 'cachetimerange'=>'0,0', 'punctualupdate'=>'0', 'hidedisplay'=>'0', 'dateline'=>'1485266568', 'notinherited'=>'0', 'isblank'=>'0',),),'style'=>array())
);