<?php

 
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}
global $comiis_config, $comiis_portal;
$comiis_config = array(
	'name' => $comiis_portal['gezi_a'],
	'dir' => 'gezi',
	'copyright' => 'http://www.comiis.com',
	'version' => '2',
	'types' => '3',
	'install' => array('block'=>array('0'=>array( 'bid'=>0, 'blockclass'=>'html_html', 'blocktype'=>'1', 'name'=>'comiis', 'title'=>'', 'classname'=>'', 'summary'=>'<div class="comiis_mh_ge4 cl"><ul><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a01.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a02.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a03.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a04.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a05.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a06.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a07.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a08.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li></ul></div>', 'uid'=>'0', 'username'=>'comiis', 'styleid'=>'0', 'blockstyle'=>'', 'picwidth'=>'0', 'picheight'=>'0', 'target'=>'blank', 'dateformat'=>'Y-m-d', 'dateuformat'=>'0', 'script'=>'blank', 'param'=>array( 'content'=>'<div class="comiis_mh_ge4 cl"><ul><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a01.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a02.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a03.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a04.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a05.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a06.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a07.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li><li><a href="#"><img src="source/plugin/comiis_app_portal/image/a08.png" class="vm"><p>'.$comiis_portal['gezi_b'].'</p></a></li></ul></div>', 'items'=>10,), 'shownum'=>'10', 'cachetime'=>'0', 'cachetimerange'=>'0,0', 'punctualupdate'=>'0', 'hidedisplay'=>'0', 'dateline'=>'1485143621', 'notinherited'=>'0', 'isblank'=>'0',),),'style'=>array())
);